Repository apache/skywalking-grafana-plugins, pull requests merged in 2023-05, with the labels that each got.

#1 build(ci): update yaml for checking license
  .github/workflows/is-compatible.yml
  .github/workflows/nodejs.yml
  .licenserc.yaml
  .nvmrc
  package.json
  src/plugin.json
Labels: enhancement

#3 Polish README.md
  .asf.yaml
  README.md
  package.json
Labels: documentation

#5 Add a NOTICE as Grafana itself is AGPL licensed
  .asf.yaml
  .config/Dockerfile
  README.md
Labels: documentation

#7 fix: update edge metrics
  src/datasource.ts
  src/types.ts
Labels: bug

#8 feat: add username and password
  src/components/ConfigEditor.tsx
  src/constant.ts
  src/datasource.ts
  src/plugin.json
  src/types.ts
Labels: enhancement

#9 fix: logo cannot be displayed
  .github/workflows/nodejs.yml
  src/img/logo.svg
Labels: bug

#11 feat: add small logo
  src/img/logo-sw.svg
  src/plugin.json
Labels: enhancement

#12 docs: file a release document
  .github/workflows/release.yml
  .gitignore
  Makefile
  release.md
Labels: documentation, enhancement

#13 build: update release file
  Makefile
Labels: enhancement

#15 fix: use OAP timezone instead of grafana ui timezone
  src/constant.ts
  src/datasource.ts
Labels: bug
